### ISSUE TITLE
install issue (without Fortran)

### ISSUE THREAD

**Issue by germasch** [ornladios/ADIOS2#1190]
I'm building adios2 with ninja (though I don't think that's related).

When I do `ninja install` (should be same as `make install` for most users):
```
[... installs stuff fine]
Configuring adios2-config dummy CMake project
[...]
-- Checking whether /opt/local/bin/gfortran supports Fortran 90
-- Checking whether /opt/local/bin/gfortran supports Fortran 90 -- yes
-- Configuring done
CMake Error at CMakeLists.txt:31 (add_executable):
  Target "with_Fortran" links to target "adios2::adios2_f" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```
I suppose that is because I'm building adios2 without fortran support:
```
  Features:
    Library Type: shared
    Build Type:   Release
    Testing: ON
    Build Options:
      BZip2    : ON
      ZFP      : OFF
      SZ       : OFF
      MGARD    : OFF
      MPI      : ON
      DataMan  : ON
      WDM      : ON
      SST      : ON
      ZeroMQ   : ON
      HDF5     : ON
      Python   : ON
      Fortran  : OFF
      SysVShMem: ON
      Endian_Reverse: OFF
```
(I didn't tell it anything about Fortran, it came up with the OFF by itself, which is fine by me. But it'd be nice for installing to succeed in this case.)

**Comment by williamfgc** [comment]
@chuckatkins I can reproduce, when configuring with ninja, cmake can't find the Fortran compilers for some reason:
```
-- Looking for a Fortran compiler
-- Looking for a Fortran compiler - NOTFOUND
 Build Options:
      BZip2    : ON
      ZFP      : ON
      SZ       : ON
      MGARD    : ON
      MPI      : ON
      DataMan  : ON
      WDM      : ON
      SST      : ON
      ZeroMQ   : ON
      HDF5     : ON
      Python   : ON
      Fortran  : OFF
      SysVShMem: ON
      Endian_Reverse: OFF
```

**Comment by germasch** [comment]
I can confirm that I have the same behavior as @williamfgc: cmake with Makefiles detects Fortran, but with ninja it doesn't. Lucky I mentioned using ninja, since I would have bet just about anything that the issue doesn't have anything to do with it...

**Comment by chuckatkins** [comment]
@germasch Can you please check that the issue is fixed in release?  It should be working now after #1191

**Comment by germasch** [comment]
@chuckatkins It actually still doesn't work, same error. I think it fails before your changes, that is here:
```
echo "Configuring adios2-config dummy CMake project"
if ! ${CMAKE} -G "Unix Makefiles" ${SOURCE_DIR} ${EXTRA_CMAKE_ARGS}
then
  echo "Failed"
  exit 1
fi
```
If it said `-G Ninja` that would most likely fix it for me, but that's obviously not the right solution. I don't really understand what's going on in the build at install time, but it generally seems iffy to me to build the project with some set of cmake configuration, but then extract the config out of a second cmake configuration run, which might well end up being different (as it did here). I mean, I could also have configured my adios2 build explicitly with different options and I don't see how those would propagate into the second cmake run, either.




 I don't actually understand what's going on in the build

**Comment by chuckatkins** [comment]
The post-install step takes a dummy CMake project that uses ADIOS and configures it, pointing to the new installation, and uses a verbose build to extract what the underlying compile and link flags are to use ADIOS.  This let's us generate the `adios2-config` shell script at install time that non-cmake applications can use`

I just tested this with the current release branch and i was able to have it work after that change was merged in:

Verify the commit is in the source tree:
```
chuck.atkins@deepthought release]$ git show HEAD
commit cf6ce71b1baa6b1847a855d6c368b9dd0a02e856
Merge: dfa36cd9 92e04d70
Author: Chuck Atkins <chuck.atkins@kitware.com>
Date:   Fri Feb 15 10:26:21 2019 -0500

    Merge pull request #1191 from chuckatkins/fix-install-without-fortran
    
    Make generation of adios2-config work without Fortran enabled

[chuck.atkins@deepthought release]$ 
```

Configure:
```
[chuck.atkins@deepthought work]$ cmake -DADIOS2_BUILD_{TESTING,EXAMPLES}=OFF -DADIOS2_USE_Fortran=OFF -DCMAKE_INSTALL_PREFIX=$PWD/../../install/work ../../source/release -G Ninja
...
ADIOS2 build configuration:
  ADIOS Version: 2.3.0
  C++ Compiler : GNU 8.2.0 
    /opt/ohpc/pub/compiler/gcc/8.2.0/bin/g++

  Installation prefix: /home/khq.kitware.com/chuck.atkins/Code/adios2/install/work
        bin: bin
        lib: lib64
    include: include
      cmake: lib64/cmake/adios2
     python: lib64/python3.4/site-packages

  Features:
    Library Type: shared
    Build Type:   Release
    Testing: OFF
    Build Options:
      BZip2    : ON
      ZFP      : OFF
      SZ       : OFF
      MGARD    : OFF
      MPI      : OFF
      DataMan  : ON
      SST      : ON
      ZeroMQ   : ON
      HDF5     : ON
      Python   : ON
      Fortran  : OFF
      SysVShMem: ON
      Endian_Reverse: OFF

-- Configuring done
-- Generating done
-- Build files have been written to: /home/khq.kitware.com/chuck.atkins/Code/adios2/build/work
[chuck.atkins@deepthought work]$
```

Build:
```
[chuck.atkins@deepthought work]$ ninja-build
...
[chuck.atkins@deepthought work]$
```

Install:
```
[chuck.atkins@deepthought work]$ ninja-build install
...
tmp/tmp.pwaG8jEvWr ~/Code/adios2/build/work
Configuring adios2-config dummy CMake project
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /opt/ohpc/pub/compiler/gcc/8.2.0/bin/gcc
-- Check for working C compiler: /opt/ohpc/pub/compiler/gcc/8.2.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/ohpc/pub/compiler/gcc/8.2.0/bin/g++
-- Check for working CXX compiler: /opt/ohpc/pub/compiler/gcc/8.2.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found adios2: /home/khq.kitware.com/chuck.atkins/Code/adios2/install/work/lib64/cmake/adios2/adios2-config.cmake (found version "2.3.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tmp.pwaG8jEvWr
Extacting ADIOS flags for C bindings
  Without ADIOS
  With ADIOS
  Extracting diff
  Exporting
Extacting ADIOS flags for C++ bindings
  Without ADIOS
  With ADIOS
  Extracting diff
  Exporting
Writing /home/khq.kitware.com/chuck.atkins/Code/adios2/install/work/bin/adios2-config
~/Code/adios2/build/work
[chuck.atkins@deepthought work]$ 
```

So this still doesn't work for you, even from the current release and / or master?

**Comment by germasch** [comment]
@chuckatkins  Well, it didn't, but a bunch of builds later, it looks like it is fixed after all: When configure with CMAKE_INSTALL_PREFIX where my previously failed installation went, it still fails the install. But if I install into a new, clean, location it now succeeds. Thanks!

**Comment by chuckatkins** [comment]
The CMake package config files changed a bit do you can't just overwrite a previous install since there will still be some package config files leftover from the previous install. I'll make sure to update the release notes for the upcoming 2.3.1 patch release accordingly.

Glad it works for you now!

**Comment by chuckatkins** [comment]
Thinking a little more about it, I think I can add a pre-install step that cleans up any stale ADIOS CMake configs in the destination leftover from a previous install.
