### ISSUE TITLE
Error build ADIOS2 2.4.1, unknown type name 'INT4'

### ISSUE THREAD

**Issue by ChrocheMisawa** [ornladios/ADIOS2#1738]
Hi guys, I'm new to ADIOS2,
When I tried to install ADIOS2, I got error making the package, I wonder why it is happening(2nd picture) and how do I solve it? 

the system is WSL2

Thanks very much!
Chen

![) {62B$N{4 AY_$Q(4 3$H](https://user-images.githubusercontent.com/47645670/64903737-48ffcd00-d68c-11e9-8e0a-144a490a99a6.png)
![image](https://user-images.githubusercontent.com/47645670/64903745-574de900-d68c-11e9-9a03-fdcdfd0ac481.png)

**Comment by JasonRuonanWang** [comment]
What compiler did you use?

**Comment by ChrocheMisawa** [comment]
> What compiler did you use?
gcc 8.3.0

if this is what you are asking

**Comment by JasonRuonanWang** [comment]
We will probably need @eisenhauer to come back and have a look. Before that, you can try temporarily disabling SST if you don't need staging, and see how it works. 

cmake -DADIOS2_USE_SST=OFF

**Comment by ChrocheMisawa** [comment]
> cmake -DADIOS2_USE_SST=OFF

Thanks! with SST disabled, no further error observed yet.
Although I need to do "sudo make install" instead of "make install"
is this normal?

**Comment by JasonRuonanWang** [comment]
The default installation directory is /usr/local so if you don't have writer permissions then you will need to sudo. I guess this is a cmake default behavior. So nothing wrong about it. If you want to install it to your personal directory where you have write permission, you can add 

-DCMAKE_INSTALL_PREFIX=/your/dir

in the cmake command

**Comment by eisenhauer** [comment]
Hi Chen,

Hmm.   WSL2 is a new version of WSL?  If so, you might be the first to try this.  Scott Klasky is one of the few that has messed with WSL.  I don't think we do regular testing there.  

Here, something funky is going on here with respect to CMake figuring out the size of int.  Either sizeof(int) != 4, or the cmake failed or something like that.  But it's going to take some deeper digging into the CMake-generated config.h, probably in build/thirdparty/ffs/ffs.  Maybe you can share the SIZEOF_INT value that is #defined there?  (Or maybe not defined there if something has gone seriously wrong.). 

(I'm currently in an airport departure lounge in Athens, so I'm not so helpful until I'm back in the US.)

g

**Comment by ChrocheMisawa** [comment]
> Hi Chen,
> 
> Hmm. WSL2 is a new version of WSL? If so, you might be the first to try this. Scott Klasky is one of the few that has messed with WSL. I don't think we do regular testing there.
> 
> Here, something funky is going on here with respect to CMake figuring out the size of int. Either sizeof(int) != 4, or the cmake failed or something like that. But it's going to take some deeper digging into the CMake-generated config.h, probably in build/thirdparty/ffs/ffs. Maybe you can share the SIZEOF_INT value that is #defined there? (Or maybe not defined there if something has gone seriously wrong.).
> 
> (I'm currently in an airport departure lounge in Athens, so I'm not so helpful until I'm back in the US.)
> 
> g

Hi, I think wsl and wsl2 should not be to much different and everything works like a normal linux for me. (I'm was mainly running MOOSE (from INL) in wsl)
But sometimes wsl may not have some pre-built libraries and may cause problem, I guess.



Regarding to my issue, I think below is where the error first initiated:
![image](https://user-images.githubusercontent.com/47645670/64905066-c7666a00-d6a0-11e9-99b4-136493e10219.png)

**Comment by ChrocheMisawa** [comment]
> Hi Chen,
> 
> Hmm. WSL2 is a new version of WSL? If so, you might be the first to try this. Scott Klasky is one of the few that has messed with WSL. I don't think we do regular testing there.
> 
> Here, something funky is going on here with respect to CMake figuring out the size of int. Either sizeof(int) != 4, or the cmake failed or something like that. But it's going to take some deeper digging into the CMake-generated config.h, probably in build/thirdparty/ffs/ffs. Maybe you can share the SIZEOF_INT value that is #defined there? (Or maybe not defined there if something has gone seriously wrong.).
> 
> (I'm currently in an airport departure lounge in Athens, so I'm not so helpful until I'm back in the US.)
> 
> g

I'm using ADIOS2 for LAMMPS, and with SST disabled, I don't have any issue using LAMMPS for now, so there is no hurry. Thank you guys for helping :)

**Comment by eisenhauer** [comment]
Yes, that is the point of the problem, you can perhaps see why I asked for the value of SIZEOF_INT in the config.h file.  Generally, sizeof(int) should be 4.  Somehow here it's not, or CMake thought it was not.  The question is why...  But if you're set for the moment, we can sort that out more leisurely...

**Comment by chuckatkins** [comment]
@eisenhauer rather than relying on compile time checks, can ffs be made to use the fixed width integer types instead, since it seems like that's what's it trying to accomplish anyways?

**Comment by williamfgc** [comment]
From our conversation, this should be fixed for the release as it's preventing building adios2 with gcc8.3.0

**Comment by chuckatkins** [comment]
@williamfgc our CI is building with gcc 8.3

**Comment by chuckatkins** [comment]
@ChrocheMisawa WSL2 as in `Windows Subsystem For Linux 2`?  If that's the case, which distro is it configured to use?

**Comment by eisenhauer** [comment]
This issue hasn't been updated for a long time, with no info coming in that the problem still exists...  If it does, please re-open.
